try {
  throw 0;
} catch (_unused) {
  console.log("it failed, but this code executes");
}
